# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: GZNL - RNA puzzles
email: rnapuzzles@gzlab.ac.cn
description: > # this means to ignore newlines until "baseurl:"
  The lab website of Zhichao Miao lab.
baseurl: ""
url: ""

include:
  - _data
  - _includes
  - _layouts
  - _pages
  - _plugins
  - _posts
  - _sass
  - blog
  - cifFiles
  - css
  - fonts
  - images
  - javascripts
  - js
  - pdbFiles
  - show
  - stylesheets
  - CNAME

category_dir: blog/categories
category_title_prefix: " "

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false



# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: false
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links


# Global
# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:  # 如果没有 Email 订阅链接，则可以留空
# RSS feeds can list your email address if you like
email: miao_zhichao@gzlab.ac.cn
